version: '3.2'
services:
  # Authentication
  auth:
    build: 
      context: './auth/auth-php/'
      dockerfile: Dockerfile.prod
    environment: 
      DB_HOST: "auth-db"
      DB_NAME: "${MYSQL_NAME}"
      DB_USERNAME: "${MYSQL_USERNAME}"
      DB_PASSWORD_FILE: /run/secrets/mysql_password
      AUTH_ISSUER: "${AUTH_ISSUER}"
      AUTH_PUBLIC: "${AUTH_PUBLIC}"
      AUTH_PRIVATE: "${AUTH_PRIVATE}"
    networks:
      - backend
      - play_network
    container_name: auth
  

  # Authentication database
  auth-db:
    build:
      context: './auth/auth-db/'
      dockerfile: Dockerfile.dev
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: "${MYSQL_NAME}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    container_name: auth-db

  